// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    CountDown: typeof import('./src/components/CountDown.vue')['default']
    Footer: typeof import('./src/layout/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/layout/Layout.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    Row: typeof import('./src/components/Row.vue')['default']
    TAccordion: typeof import('./src/components/t-accordion/TAccordion.vue')['default']
    TAccordionContent: typeof import('./src/components/t-accordion/TAccordionContent.vue')['default']
    TAccordionExample: typeof import('./src/components/t-accordion/TAccordionExample.vue')['default']
    TAccordionHeader: typeof import('./src/components/t-accordion/TAccordionHeader.vue')['default']
    TAccordions: typeof import('./src/components/t-accordion/TAccordions.vue')['default']
  }
}

export { }
